fixed errors
PotLock/potlock-nextjs-app pull request #183
Opened 2024-10-15 21:30 UTC by Ebube111

2024-10-15 21:58 UTC, carina-akaia requested changes

2024-10-15 21:58 UTC, carina-akaia commented on src/common/ui/components/templates/page-with-banner.tsx
> +  <main className="2xl-container px-[40px] pb-12" un-w="full" un-flex="~ col">
Please use universal units instead of raw px ( in this case it'll be `px-10`, where 10 is 40 / 4 ( 1 unit is 0,25rem, which is by default 4px )

2024-10-15 21:58 UTC, carina-akaia commented on src/modules/lists/components/AccountCard.tsx
> +    <div
Please use Next's Link with href instead

2024-10-15 21:58 UTC, carina-akaia commented on src/modules/lists/components/AccountCard.tsx
> +  const handleAccountClick = useCallback(
Please use Next's Link with href instead

2024-10-16 05:04 UTC, Ebube111 commented on src/common/ui/components/templates/page-with-banner.tsx
> +  <main className="2xl-container px-[40px] pb-12" un-w="full" un-flex="~ col">
resolved

2024-10-16 06:49 UTC, Ebube111 commented on src/modules/lists/components/AccountCard.tsx
> +    <div
resolved

2024-10-16 06:49 UTC, Ebube111 commented on src/modules/lists/components/AccountCard.tsx
> +  const handleAccountClick = useCallback(
resolved

2024-10-16 12:33 UTC, carina-akaia approved these changes

2024-10-16 12:40 UTC, carina-akaia approved these changes

2024-10-18 05:01 UTC, merged