Bug fixes and minor improvements
PotLock/potlock-nextjs-app pull request #185
Opened 2024-10-16 17:48 UTC by carina-akaia

2024-10-17 13:21 UTC, carina-akaia commented
@race-of-sloths

2024-10-17 17:33 UTC, codingshot commented
@race-of-sloths score [1]

2024-10-17 17:36 UTC, race-of-sloths commented
### 🏆 Score recorded! 
It looks like @codingshot provided a score of [1], but based on our Fibonacci scoring rules, we've adjusted it to 0.
> [!TIP]
We accept only the following Fibonacci numbers [0, 1, 2, 3, 5, 8, 13] for scoring

2024-10-21 04:32 UTC, Ebube111 requested changes
Code looks good. but we need to hide the List tab from the nav. it's not ready till the contract changes are updated

2024-10-21 04:32 UTC, Ebube111 commented on src/modules/core/components/Nav.tsx
> +  },
Don't show the list tab just yet, @Prometheo  is has not deployed his changes to mainnet, most things are breaking

2024-10-21 04:32 UTC, Ebube111 commented on src/modules/donation/hooks/forms.ts
> +  console.log(JSON.stringify(self.formState, null, 2));
do you need cleanup?

2024-10-21 04:33 UTC, Ebube111 commented on src/modules/core/components/Nav.tsx
> +  },
or does the disabled prop hide it?

2024-10-21 04:34 UTC, Ebube111 approved these changes

2024-10-21 13:22 UTC, carina-akaia commented on src/modules/core/components/Nav.tsx
> +  },
No, but it should be non-clickable for regular users, do we really have to comment it out?

2024-10-22 02:52 UTC, carina-akaia commented on src/modules/donation/hooks/forms.ts
> +  console.log(JSON.stringify(self.formState, null, 2));
This time I'll need it in the next PR I'll open soon enough

2024-10-22 06:30 UTC, Ebube111 commented on src/modules/donation/hooks/forms.ts
> +  console.log(JSON.stringify(self.formState, null, 2));
Noted

2024-10-22 06:31 UTC, Ebube111 commented on src/modules/core/components/Nav.tsx
> +  },
Alright sounds good

2024-10-22 08:11 UTC, merged