Payout challenge & Pot Feeds FIlter
PotLock/potlock-nextjs-app pull request #264
Opened 2024-11-29 10:32 UTC by Ebube111

2024-11-29 11:32 UTC, carina-akaia requested changes

2024-11-29 11:32 UTC, carina-akaia commented on src/pages/pot/[potId]/feeds.tsx
> +import { Application, ApplicationStatus, potClient } from "@/common/contracts/core";
Use `PotApplicationStatus` instead as it's up do date since it's generated from the indexer schema ( as opposed to the manually created contract interface )

2024-11-29 11:32 UTC, carina-akaia commented on src/pages/pot/[potId]/payouts.tsx
> +          className={`${showChallenges ? "md:block" : "hidden"} md:hidden md:w-[33%] md:max-w-[33%] w-full transition-all duration-500 ease-in-out`}
Use `cn` function from `@/common/ui/utils` instead of template literals

// make sure `hidden` class works, because it might not, in which case use the "non-displayed" class

2024-11-29 11:32 UTC, carina-akaia commented on src/pages/pot/[potId]/payouts.tsx
> +        className={`flex w-full flex-col items-center p-0 ${showChallenges ? "md:w-[65%]" : ""} justify-between transition-all duration-500 ease-in-out`}
Use `cn` function from `@/common/ui/utils` instead of template literals

2024-11-29 11:32 UTC, carina-akaia commented on src/pages/pot/[potId]/feeds.tsx
> +            className={`border px-3 py-1 text-sm transition-all duration-200 ease-in-out ${tab === selectedTab.value ? "rounded-sm border-[#F4B37D] bg-[#FCE9D5]  text-[#91321B]" : "border-[#DBDBDB] b
Use `cn` function from `@/common/ui/utils` instead of template literals

2024-11-29 11:32 UTC, carina-akaia commented on src/pages/pot/[potId]/payouts.tsx
> +                className={`${showChallenges ? "md:rotate-265 rotate-180" : "md:rotate-90 rotate:45"} ml-3 transition-all duration-300 ease-in-out`}
Use `cn` function from `@/common/ui/utils` instead of template literals

2024-11-29 11:32 UTC, carina-akaia commented on src/pages/pot/[potId]/payouts.tsx
> +        className={`${showChallenges ? "md:block" : "hidden"} md:w-[33%] md:max-w-[33%] hidden w-full transition-all duration-500 ease-in-out`}
Use `cn` function from `@/common/ui/utils` instead of template literals

// make sure `hidden` class works, because it might not, in which case use the "non-displayed" class, also nota that it's duplicated here

2024-11-29 11:32 UTC, carina-akaia commented on src/modules/pot/hooks/permissions.ts
Remove this file, it has been replaced with `hooks/clearance.ts` that contains an updated version of the `usePotUserPermissions` hook amongst other things

2024-11-29 11:32 UTC, carina-akaia commented on src/modules/pot/components/PotTimelineFragment.tsx
> +    background: white;
Remove this line

2024-11-29 11:32 UTC, carina-akaia commented on src/modules/pot/components/PayoutsChallenges/PayoutsChallenges.tsx
> +            className={`border px-3 py-1 text-sm transition-all duration-200 ease-in-out ${tab === "RESOLVED" ? "rounded-sm border-[#F4B37D] bg-[#FCE9D5]  text-[#91321B]" : "border-[#DBDBDB] bg-white
Use `cn` function from `@/common/ui/utils` instead of template literals

2024-11-29 11:32 UTC, carina-akaia commented on src/modules/pot/components/PayoutsChallenges/PayoutsChallenges.tsx
> +            className={`border px-3 py-1 text-sm transition-all duration-200 ease-in-out ${tab === "UNRESOLVED" ? "rounded-sm border-[#F4B37D] bg-[#FCE9D5]  text-[#91321B]" : "border-[#DBDBDB] bg-whi
Use `cn` function from `@/common/ui/utils` instead of template literals

2024-12-02 08:28 UTC, Ebube111 commented on src/modules/pot/components/Banner.tsx
removed

2024-12-02 08:31 UTC, Ebube111 commented on src/modules/project/hooks/useProjectsFilters.ts
removed

2024-12-02 08:41 UTC, Ebube111 commented on src/modules/pot/utils/timeline.ts
removed

2024-12-02 08:59 UTC, Ebube111 commented on src/pages/pot/[potId]/feeds.tsx
> +import { Application, ApplicationStatus, potClient } from "@/common/contracts/core";
resolved

2024-12-02 11:11 UTC, Ebube111 commented on src/modules/pot/components/PotTimelineFragment.tsx
> +    background: white;
removed

2024-12-02 11:13 UTC, Ebube111 commented on src/pages/pot/[potId]/payouts.tsx
> +          className={`${showChallenges ? "md:block" : "hidden"} md:hidden md:w-[33%] md:max-w-[33%] w-full transition-all duration-500 ease-in-out`}
done

2024-12-02 11:13 UTC, Ebube111 commented on src/pages/pot/[potId]/payouts.tsx
> +        className={`flex w-full flex-col items-center p-0 ${showChallenges ? "md:w-[65%]" : ""} justify-between transition-all duration-500 ease-in-out`}
done

2024-12-02 11:14 UTC, Ebube111 commented on src/pages/pot/[potId]/payouts.tsx
> +        className={`${showChallenges ? "md:block" : "hidden"} md:w-[33%] md:max-w-[33%] hidden w-full transition-all duration-500 ease-in-out`}
handled

2024-12-02 11:15 UTC, Ebube111 commented on src/modules/pot/hooks/permissions.ts
removed

2024-12-02 11:15 UTC, Ebube111 commented on src/modules/pot/components/PayoutsChallenges/PayoutsChallenges.tsx
> +            className={`border px-3 py-1 text-sm transition-all duration-200 ease-in-out ${tab === "RESOLVED" ? "rounded-sm border-[#F4B37D] bg-[#FCE9D5]  text-[#91321B]" : "border-[#DBDBDB] bg-white
handled

2024-12-02 13:38 UTC, carina-akaia approved these changes

2024-12-02 13:40 UTC, merged