DAO Profile Enhancement & Profile Page for Regular Users (not a project)
PotLock/potlock-nextjs-app pull request #95
Opened 2024-07-29 20:29 UTC by wpdas

DAO Profile:

![Screenshot 2024-07-25 at 17 11 21](https://github.com/user-attachments/assets/ceddebc8-487a-4598-a5d6-2474ee375c73)

Profile for Regular users:

![Screenshot 2024-07-29 at 17 28 51](https://github.com/user-attachments/assets/98b9dfc1-843a-41cc-8829-826e4978572a)

2024-07-29 23:02 UTC, carina-akaia requested changes

2024-07-29 23:02 UTC, carina-akaia commented on src/modules/core/hooks/useDonationsSent.ts
> +    const allDonations_usdInfo = nearToUsdWithFallback(
Let's use `coingecko.useOneNearUsdPrice()` for USD price calculation instead, so that we don't break runtime if Coingecko doesn't respond with 200

2024-07-30 01:40 UTC, wpdas commented on src/modules/core/hooks/useDonationsSent.ts
> +        donationsData?.results.filter((donation) => {
idk why I used a filter here. Fixing.

2024-07-30 01:54 UTC, wpdas commented on src/modules/core/hooks/useDonationsSent.ts
> +        donationsData?.results.filter((donation) => {
done. fixed `useDonationsForProject` too.

2024-07-30 01:54 UTC, wpdas commented on src/modules/core/hooks/useDonationsSent.ts
> +    const allDonations_usdInfo = nearToUsdWithFallback(
done. applied this change to `useDonationsForProject` too.

2024-07-30 01:58 UTC, carina-akaia approved these changes

2024-07-30 02:02 UTC, merged